apimServiceName: apim-hh-prod-weus2
namedValues:
  - name: environment
    properties:
      displayName: environment
      value: "prod"
  - name: api_client_id
    properties:
      displayName: api_client_id
      value: "prod_client" 
backends:
  - name: echofunctionapp
    properties:
      url: "https://echo.prod.com/api"
apis:
  - name: echo-api
    properties:
      displayName: Echo API
      description: A demonstration API that echoes back the request.
      serviceUrl: "https://apim-hh-prod.azure-api.net/echo"
      path: "/echo"