openapi: 3.0.1
info:
  title: dummy
  description: ''
  version: '1.0'
servers:
  - url: https://apim-hh-dev.azure-api.net
paths:
  /testurl:
    get:
      summary: operation1
      description: operation1
      operationId: operation1
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]